# Recommendation analysis

In [1]:
import torch
import sys

from recbole.utils.utils import init_seed
from recbole.utils.logger import init_logger
from logging import getLogger
from recbole.data.utils import create_dataset
from recbole.data.utils import data_preparation
from recbole.utils.utils import get_model
import pandas as pd
import ast
import json

# Oszaleje kurwa
class WandbMock:
    def init(self, *args, **kwargs): return None
    def log(self, *args, **kwargs): return None

sys.modules['wandb'] = WandbMock()

In [2]:
MODELS = ["base.pth", "cat_titles.pth", "images.pth"]

### Import saved models

In [3]:
models = []
for model_name in MODELS:
    data = torch.load(f"../../../../../saved/{model_name}", map_location='cpu', weights_only=False)

    config = data['config']
    config.final_config_dict['data_path'] = r'\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\Amazon_Sports_and_Outdoors'
    config['device'] = 'cpu'
    config['wandb_run_name'] = 'test_run'
    config['orig_attribute_hidden_size'] = [420, 420]
    config['eval_batch_size'] = 1

    for attr, value in config.__dict__.items():
        print(f"{attr} = {value}")

    init_seed(config['seed'], config['reproducibility'])
    init_logger(config)
    logger = getLogger()
    logger.info(config)

    dataset = create_dataset(config)
    logger.info(dataset)

    train_data, valid_data, test_data = data_preparation(config, dataset)
    model1 = get_model(config['model'])(config, train_data.dataset).to(config['device'])
    logger.info(model1)

    model1.load_state_dict(data['state_dict'])
    model1.eval()
    models.append(model1)

25 Jan 20:15    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 212
state = INFO
reproducibility = True
data_path = \\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\Amazon_Sports_and_Outdoors
show_progress = True
save_dataset = False
save_dataloaders = False
benchmark_filename = None

Training Hyper Parameters:
checkpoint_dir = saved
epochs = 200
train_batch_size = 1024
learner = adam
learning_rate = 0.0001
eval_step = 2
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}
metrics = ['Recall', 'NDCG']
topk = [3, 5, 10, 20]
valid_metric = Recall@10
valid_metric_bigger = True
eval_batch_size = 1
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'zero': ['ent_id', 'ent_emb']}
unload_col = None
unused_col = None
additional_feat_suffix = ['zero']
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [5,inf)
item_inter_num_interval = [5,inf)
alias_of_user_id = None
alias_of_item_id = ['ent_id']
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = {'ent_id': 'ent_emb'}
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id

Other Hyper Parameters:
neg_sampling = None
multi_gpus = False
repeatable = True
n_layers = 3
n_heads = 8
hidden_size = 256
attribute_hidden_size = [128]
inner_size = 256
hidden_dropout_prob = 0.5
attn_dropout_prob = 0.3
hidden_act = gelu
layer_norm_eps = 1e-12
initializer_range = 0.02
selected_features = ['ent_emb']
pooling_mode = sum
loss_type = CE
weight_sharing = not
fusion_type = gate
lamdas = [5]
attribute_predictor = ['not']
MODEL_TYPE = ModelType.SEQUENTIAL
orig_attribute_hidden_size = [420, 420]
feature_type = ['static']
diffusion = {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}
lambda = 0.5
wandb_run_name = test_run
annealing = False
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
device = cpu
train_neg_sample_args = {'strategy': 'none'}
eval_neg_sample_args = {'strategy': 'full', 'distribution': 'uniform'}

parameters = {'General': ['gpu_id', 'use_gpu', 'seed', 'reproducibility', 'state', 'data_path', 'benchmark_filename', 'show_progress', 'config_file', 'save_dataset', 'save_dataloaders'], 'Training': ['epochs', 'train_batch_size', 'learner', 'learning_rate', 'training_neg_sample_num', 'training_neg_sample_distribution', 'eval_step', 'stopping_step', 'checkpoint_dir', 'clip_grad_norm', 'loss_decimal_place', 'weight_decay'], 'Evaluation': ['eval_args', 'metrics', 'topk', 'valid_metric', 'valid_metric_bigger', 'eval_batch_size', 'metric_decimal_place'], 'Dataset': ['field_separator', 'seq_separator', 'USER_ID_FIELD', 'ITEM_ID_FIELD', 'RATING_FIELD', 'TIME_FIELD', 'seq_len', 'LABEL_FIELD', 'threshold', 'NEG_PREFIX', 'ITEM_LIST_LENGTH_FIELD', 'LIST_SUFFIX', 'MAX_ITEM_LIST_LENGTH', 'POSITION_FIELD', 'HEAD_ENTITY_ID_FIELD', 'TAIL_ENTITY_ID_FIELD', 'RELATION_ID_FIELD', 'ENTITY_ID_FIELD', 'load_col', 'unload_col', 'unused_col', 'additional_feat_suffix', 'filter_inter_by_user_or_item', 'rm_dup_inter', 'val_interval', 'user_inter_num_interval', 'item_inter_num_interval', 'alias_of_user_id', 'alias_of_item_id', 'alias_of_entity_id', 'alias_of_relation_id', 'preload_weight', 'normalize_field', 'normalize_all']}
yaml_loader = <class 'yaml.loader.FullLoader'>
file_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': './recbole/data/dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'additional_feat_suffix': ['zero'], 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'zero': ['ent_id', 'ent_emb']}, 'alias_of_item_id': ['ent_id'], 'preload_weight': {'ent_id': 'ent_emb'}, 'MAX_ITEM_LIST_LENGTH': 50, 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'orig_attribute_hidden_size': [128], 'attribute_hidden_size': [128], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['ent_emb'], 'feature_type': ['static'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5], 'attribute_predictor': ['not'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'baseline_obrazek', 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'neg_sampling': None, 'annealing': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 256, 'loss_decimal_place': 4, 'metric_decimal_place': 4}
variable_config_dict = {'neg_sampling': None}
cmd_config_dict = {'gpu_id': 0, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors(image).yaml'}
external_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': './recbole/data/dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'additional_feat_suffix': ['zero'], 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'zero': ['ent_id', 'ent_emb']}, 'alias_of_item_id': ['ent_id'], 'preload_weight': {'ent_id': 'ent_emb'}, 'MAX_ITEM_LIST_LENGTH': 50, 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'orig_attribute_hidden_size': [128], 'attribute_hidden_size': [128], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['ent_emb'], 'feature_type': ['static'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5], 'attribute_predictor': ['not'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'baseline_obrazek', 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'neg_sampling': None, 'annealing': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 256, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors(image).yaml'}
model = SASRecD
model_class = <class 'recbole.model.sequential_recommender.sasrecd.SASRecD'>
dataset = Amazon_Sports_and_Outdoors
internal_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 2020, 'state': 'INFO', 'reproducibility': True, 'data_path': 'dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'epochs': 300, 'train_batch_size': 2048, 'learner': 'adam', 'learning_rate': 0.001, 'neg_sampling': {'uniform': 1}, 'eval_step': 1, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'multi_gpus': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision'], 'topk': [10], 'valid_metric': 'MRR@10', 'valid_metric_bigger': True, 'eval_batch_size': 4096, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'n_layers': 4, 'n_heads': 2, 'hidden_size': 256, 'attribute_hidden_size': [64], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['class'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'concat', 'lamdas': [10], 'attribute_predictor': 'linear', 'field_separator': '\t', 'seq_separator': ' ', 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'seq_len': None, 'LABEL_FIELD': 'label', 'threshold': None, 'NEG_PREFIX': 'neg_', 'load_col': {'inter': ['user_id', 'item_id']}, 'unload_col': None, 'unused_col': None, 'additional_feat_suffix': None, 'rm_dup_inter': None, 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[0,inf)', 'item_inter_num_interval': '[0,inf)', 'alias_of_user_id': None, 'alias_of_item_id': None, 'alias_of_entity_id': None, 'alias_of_relation_id': None, 'preload_weight': None, 'normalize_field': None, 'normalize_all': None, 'ITEM_LIST_LENGTH_FIELD': 'item_length', 'LIST_SUFFIX': '_list', 'MAX_ITEM_LIST_LENGTH': 50, 'POSITION_FIELD': 'position_id', 'HEAD_ENTITY_ID_FIELD': 'head_id', 'TAIL_ENTITY_ID_FIELD': 'tail_id', 'RELATION_ID_FIELD': 'relation_id', 'ENTITY_ID_FIELD': 'entity_id', 'benchmark_filename': None, 'MODEL_TYPE': <ModelType.SEQUENTIAL: 2>}
final_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': '\\\\wsl.localhost\\Ubuntu\\home\\piotrs\\Uni\\SequentialRecommendation\\recbole\\data\\dataset\\Amazon_Sports_and_Outdoors', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'neg_sampling': None, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'multi_gpus': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 1, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'attribute_hidden_size': [128], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['ent_emb'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5], 'attribute_predictor': ['not'], 'field_separator': '\t', 'seq_separator': ' ', 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'seq_len': None, 'LABEL_FIELD': 'label', 'threshold': None, 'NEG_PREFIX': 'neg_', 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'zero': ['ent_id', 'ent_emb']}, 'unload_col': None, 'unused_col': None, 'additional_feat_suffix': ['zero'], 'rm_dup_inter': None, 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'alias_of_user_id': None, 'alias_of_item_id': ['ent_id'], 'alias_of_entity_id': None, 'alias_of_relation_id': None, 'preload_weight': {'ent_id': 'ent_emb'}, 'normalize_field': None, 'normalize_all': None, 'ITEM_LIST_LENGTH_FIELD': 'item_length', 'LIST_SUFFIX': '_list', 'MAX_ITEM_LIST_LENGTH': 50, 'POSITION_FIELD': 'position_id', 'HEAD_ENTITY_ID_FIELD': 'head_id', 'TAIL_ENTITY_ID_FIELD': 'tail_id', 'RELATION_ID_FIELD': 'relation_id', 'ENTITY_ID_FIELD': 'entity_id', 'benchmark_filename': None, 'MODEL_TYPE': <ModelType.SEQUENTIAL: 2>, 'orig_attribute_hidden_size': [420, 420], 'feature_type': ['static'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'test_run', 'annealing': False, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors(image).yaml', 'MODEL_INPUT_TYPE': <InputType.POINTWISE: 1>, 'eval_type': <EvaluatorType.RANKING: 1>, 'device': 'cpu', 'train_neg_sample_args': {'strategy': 'none'}, 'eval_neg_sample_args': {'strategy': 'full', 'distribution': 'uniform'}}

\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:446: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].fillna(value='', inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:446: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].fillna(value='', inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:965: FutureWarning: using <built-in function len> in Series.agg cannot aggregate and has been deprecated. Use Series.transform to keep behavior unchanged.
  split_point = np.cumsum(feat[field].agg(len))[:-1]
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:568: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:570: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
25 Jan 20:15    INFO  Amazon_Sports_and_Outdoors
The number of users: 35599
Average actions of users: 8.324540704533963
The number of items: 18358
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465569853714%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp', 'title', 'price', 'brand', 'categories', 'sales_type', 'sales_rank', 'ent_id', 'ent_emb']
25 Jan 20:15    INFO  [Training]: train_batch_size = [1024] negative sampling: [None]
25 Jan 20:15    INFO  [Evaluation]: eval_batch_size = [1] eval_args: [{'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}]
25 Jan 20:15    INFO  SASRecD(
  (item_embedding): Embedding(18358, 256, padding_idx=0)
  (position_embedding): Embedding(50, 256)
  (feature_embed_layer_list): ModuleList(
    (0): Embedding(18358, 128)
  )
  (trm_encoder): DIFTransformerEncoder(
    (layer): ModuleList(
      (0-2): 3 x DIFTransformerLayer(
        (multi_head_attention): DIFMultiHeadAttention(
          (query): Linear(in_features=256, out_features=256, bias=True)
          (key): Linear(in_features=256, out_features=256, bias=True)
          (value): Linear(in_features=256, out_features=256, bias=True)
          (query_p): Linear(in_features=256, out_features=256, bias=True)
          (key_p): Linear(in_features=256, out_features=256, bias=True)
          (query_layers): ModuleList(
            (0): Linear(in_features=128, out_features=128, bias=True)
          )
          (key_layers): ModuleList(
            (0): Linear(in_features=128, out_features=128, bias=True)
          )
          (fusion_layer): VanillaAttention(
            (projection): Sequential(
              (0): Linear(in_features=50, out_features=50, bias=True)
              (1): ReLU(inplace=True)
              (2): Linear(in_features=50, out_features=1, bias=True)
            )
          )
          (attn_dropout): Dropout(p=0.3, inplace=False)
          (dense): Linear(in_features=256, out_features=256, bias=True)
          (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=256, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=256, bias=True)
          (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
  (ap): ModuleList(
    (0): None
  )
  (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (loss_fct): CrossEntropyLoss()
  (attribute_loss_fct): BCEWithLogitsLoss()
)
Trainable parameters: 6401915

parameters = {'General': ['gpu_id', 'use_gpu', 'seed', 'reproducibility', 'state', 'data_path', 'benchmark_filename', 'show_progress', 'config_file', 'save_dataset', 'save_dataloaders'], 'Training': ['epochs', 'train_batch_size', 'learner', 'learning_rate', 'training_neg_sample_num', 'training_neg_sample_distribution', 'eval_step', 'stopping_step', 'checkpoint_dir', 'clip_grad_norm', 'loss_decimal_place', 'weight_decay'], 'Evaluation': ['eval_args', 'metrics', 'topk', 'valid_metric', 'valid_metric_bigger', 'eval_batch_size', 'metric_decimal_place'], 'Dataset': ['field_separator', 'seq_separator', 'USER_ID_FIELD', 'ITEM_ID_FIELD', 'RATING_FIELD', 'TIME_FIELD', 'seq_len', 'LABEL_FIELD', 'threshold', 'NEG_PREFIX', 'ITEM_LIST_LENGTH_FIELD', 'LIST_SUFFIX', 'MAX_ITEM_LIST_LENGTH', 'POSITION_FIELD', 'HEAD_ENTITY_ID_FIELD', 'TAIL_ENTITY_ID_FIELD', 'RELATION_ID_FIELD', 'ENTITY_ID_FIELD', 'load_col', 'unload_col', 'unused_col', 'additional_feat_suffix', 'filter_inter_by_user_or_item', 'rm_dup_inter', 'val_interval', 'user_inter_num_interval', 'item_inter_num_interval', 'alias_of_user_id', 'alias_of_item_id', 'alias_of_entity_id', 'alias_of_relation_id', 'preload_weight', 'normalize_field', 'normalize_all']}
yaml_loader = <class 'yaml.loader.FullLoader'>
file_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': './recbole/data/dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'additional_feat_suffix': ['title'], 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'title': ['ent_id', 'ent_emb']}, 'alias_of_item_id': ['ent_id'], 'preload_weight': {'ent_id': 'ent_emb'}, 'MAX_ITEM_LIST_LENGTH': 50, 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'orig_attribute_hidden_size': [128, 64], 'attribute_hidden_size': [128, 64], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['ent_emb', 'categories'], 'feature_type': ['static', 'categorical'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5, 5], 'attribute_predictor': ['cos_sim', 'linear'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'titles_categories_obrazek', 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'neg_sampling': None, 'annealing': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 256, 'loss_decimal_place': 4, 'metric_decimal_place': 4}
variable_config_dict = {'neg_sampling': None}
cmd_config_dict = {'gpu_id': 0, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors.yaml'}
external_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': './recbole/data/dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'additional_feat_suffix': ['title'], 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'title': ['ent_id', 'ent_emb']}, 'alias_of_item_id': ['ent_id'], 'preload_weight': {'ent_id': 'ent_emb'}, 'MAX_ITEM_LIST_LENGTH': 50, 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'orig_attribute_hidden_size': [128, 64], 'attribute_hidden_size': [128, 64], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['ent_emb', 'categories'], 'feature_type': ['static', 'categorical'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5, 5], 'attribute_predictor': ['cos_sim', 'linear'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'titles_categories_obrazek', 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'neg_sampling': None, 'annealing': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 256, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors.yaml'}
model = SASRecD
model_class = <class 'recbole.model.sequential_recommender.sasrecd.SASRecD'>
dataset = Amazon_Sports_and_Outdoors
internal_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 2020, 'state': 'INFO', 'reproducibility': True, 'data_path': 'dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'epochs': 300, 'train_batch_size': 2048, 'learner': 'adam', 'learning_rate': 0.001, 'neg_sampling': {'uniform': 1}, 'eval_step': 1, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'multi_gpus': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision'], 'topk': [10], 'valid_metric': 'MRR@10', 'valid_metric_bigger': True, 'eval_batch_size': 4096, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'n_layers': 4, 'n_heads': 2, 'hidden_size': 256, 'attribute_hidden_size': [64], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['class'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'concat', 'lamdas': [10], 'attribute_predictor': 'linear', 'field_separator': '\t', 'seq_separator': ' ', 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'seq_len': None, 'LABEL_FIELD': 'label', 'threshold': None, 'NEG_PREFIX': 'neg_', 'load_col': {'inter': ['user_id', 'item_id']}, 'unload_col': None, 'unused_col': None, 'additional_feat_suffix': None, 'rm_dup_inter': None, 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[0,inf)', 'item_inter_num_interval': '[0,inf)', 'alias_of_user_id': None, 'alias_of_item_id': None, 'alias_of_entity_id': None, 'alias_of_relation_id': None, 'preload_weight': None, 'normalize_field': None, 'normalize_all': None, 'ITEM_LIST_LENGTH_FIELD': 'item_length', 'LIST_SUFFIX': '_list', 'MAX_ITEM_LIST_LENGTH': 50, 'POSITION_FIELD': 'position_id', 'HEAD_ENTITY_ID_FIELD': 'head_id', 'TAIL_ENTITY_ID_FIELD': 'tail_id', 'RELATION_ID_FIELD': 'relation_id', 'ENTITY_ID_FIELD': 'entity_id', 'benchmark_filename': None, 'MODEL_TYPE': <ModelType.SEQUENTIAL: 2>}
final_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': '\\\\wsl.localhost\\Ubuntu\\home\\piotrs\\Uni\\SequentialRecommendation\\recbole\\data\\dataset\\Amazon_Sports_and_Outdoors', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'neg_sampling': None, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'multi_gpus': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 1, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'attribute_hidden_size': [128, 64], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['ent_emb', 'categories'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5, 5], 'attribute_predictor': ['cos_sim', 'linear'], 'field_separator': '\t', 'seq_separator': ' ', 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'seq_len': None, 'LABEL_FIELD': 'label', 'threshold': None, 'NEG_PREFIX': 'neg_', 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'title': ['ent_id', 'ent_emb']}, 'unload_col': None, 'unused_col': None, 'additional_feat_suffix': ['title'], 'rm_dup_inter': None, 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'alias_of_user_id': None, 'alias_of_item_id': ['ent_id'], 'alias_of_entity_id': None, 'alias_of_relation_id': None, 'preload_weight': {'ent_id': 'ent_emb'}, 'normalize_field': None, 'normalize_all': None, 'ITEM_LIST_LENGTH_FIELD': 'item_length', 'LIST_SUFFIX': '_list', 'MAX_ITEM_LIST_LENGTH': 50, 'POSITION_FIELD': 'position_id', 'HEAD_ENTITY_ID_FIELD': 'head_id', 'TAIL_ENTITY_ID_FIELD': 'tail_id', 'RELATION_ID_FIELD': 'relation_id', 'ENTITY_ID_FIELD': 'entity_id', 'benchmark_filename': None, 'MODEL_TYPE': <ModelType.SEQUENTIAL: 2>, 'orig_attribute_hidden_size': [420, 420], 'feature_type': ['static', 'categorical'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'test_run', 'annealing': False, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors.yaml', 'MODEL_INPUT_TYPE': <InputType.POINTWISE: 1>, 'eval_type': <EvaluatorType.RANKING: 1>, 'device': 'cpu', 'train_neg_sample_args': {'strategy': 'none'}, 'eval_neg_sample_args': {'strategy': 'full', 'distribution': 'uniform'}}

25 Jan 20:15    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 212
state = INFO
reproducibility = True
data_path = \\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\Amazon_Sports_and_Outdoors
show_progress = True
save_dataset = False
save_dataloaders = False
benchmark_filename = None

Training Hyper Parameters:
checkpoint_dir = saved
epochs = 200
train_batch_size = 1024
learner = adam
learning_rate = 0.0001
eval_step = 2
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}
metrics = ['Recall', 'NDCG']
topk = [3, 5, 10, 20]
valid_metric = Recall@10
valid_metric_bigger = True
eval_batch_size = 1
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'title': ['ent_id', 'ent_emb']}
unload_col = None
unused_col = None
additional_feat_suffix = ['title']
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [5,inf)
item_inter_num_interval = [5,inf)
alias_of_user_id = None
alias_of_item_id = ['ent_id']
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = {'ent_id': 'ent_emb'}
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id

Other Hyper Parameters:
neg_sampling = None
multi_gpus = False
repeatable = True
n_layers = 3
n_heads = 8
hidden_size = 256
attribute_hidden_size = [128, 64]
inner_size = 256
hidden_dropout_prob = 0.5
attn_dropout_prob = 0.3
hidden_act = gelu
layer_norm_eps = 1e-12
initializer_range = 0.02
selected_features = ['ent_emb', 'categories']
pooling_mode = sum
loss_type = CE
weight_sharing = not
fusion_type = gate
lamdas = [5, 5]
attribute_predictor = ['cos_sim', 'linear']
MODEL_TYPE = ModelType.SEQUENTIAL
orig_attribute_hidden_size = [420, 420]
feature_type = ['static', 'categorical']
diffusion = {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}
lambda = 0.5
wandb_run_name = test_run
annealing = False
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
device = cpu
train_neg_sample_args = {'strategy': 'none'}
eval_neg_sample_args = {'strategy': 'full', 'distribution': 'uniform'}


\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:446: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].fillna(value='', inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:446: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].fillna(value='', inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:965: FutureWarning: using <built-in function len> in Series.agg cannot aggregate and has been deprecated. Use Series.transform to keep behavior unchanged.
  split_point = np.cumsum(feat[field].agg(len))[:-1]
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:568: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:570: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
25 Jan 20:15    INFO  Amazon_Sports_and_Outdoors
The number of users: 35599
Average actions of users: 8.324540704533963
The number of items: 18358
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465569853714%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp', 'title', 'price', 'brand', 'categories', 'sales_type', 'sales_rank', 'ent_id', 'ent_emb']
25 Jan 20:15    INFO  [Training]: train_batch_size = [1024] negative sampling: [None]
25 Jan 20:15    INFO  [Evaluation]: eval_batch_size = [1] eval_args: [{'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}]
25 Jan 20:15    INFO  SASRecD(
  (item_embedding): Embedding(18358, 256, padding_idx=0)
  (position_embedding): Embedding(50, 256)
  (feature_embed_layer_list): ModuleList(
    (0): Embedding(18358, 128)
    (1): FeatureSeqEmbLayer()
  )
  (trm_encoder): DIFTransformerEncoder(
    (layer): ModuleList(
      (0-2): 3 x DIFTransformerLayer(
        (multi_head_attention): DIFMultiHeadAttention(
          (query): Linear(in_features=256, out_features=256, bias=True)
          (key): Linear(in_features=256, out_features=256, bias=True)
          (value): Linear(in_features=256, out_features=256, bias=True)
          (query_p): Linear(in_features=256, out_features=256, bias=True)
          (key_p): Linear(in_features=256, out_features=256, bias=True)
          (query_layers): ModuleList(
            (0): Linear(in_features=128, out_features=128, bias=True)
            (1): Linear(in_features=64, out_features=64, bias=True)
          )
          (key_layers): ModuleList(
            (0): Linear(in_features=128, out_features=128, bias=True)
            (1): Linear(in_features=64, out_features=64, bias=True)
          )
          (fusion_layer): VanillaAttention(
            (projection): Sequential(
              (0): Linear(in_features=50, out_features=50, bias=True)
              (1): ReLU(inplace=True)
              (2): Linear(in_features=50, out_features=1, bias=True)
            )
          )
          (attn_dropout): Dropout(p=0.3, inplace=False)
          (dense): Linear(in_features=256, out_features=256, bias=True)
          (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=256, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=256, bias=True)
          (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
  (ap): ModuleList(
    (0): Linear(in_features=256, out_features=128, bias=True)
    (1): Linear(in_features=256, out_features=1876, bias=True)
  )
  (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (loss_fct): CrossEntropyLoss()
  (attribute_loss_fct): BCEWithLogitsLoss()
)
Trainable parameters: 6941903

parameters = {'General': ['gpu_id', 'use_gpu', 'seed', 'reproducibility', 'state', 'data_path', 'benchmark_filename', 'show_progress', 'config_file', 'save_dataset', 'save_dataloaders'], 'Training': ['epochs', 'train_batch_size', 'learner', 'learning_rate', 'training_neg_sample_num', 'training_neg_sample_distribution', 'eval_step', 'stopping_step', 'checkpoint_dir', 'clip_grad_norm', 'loss_decimal_place', 'weight_decay'], 'Evaluation': ['eval_args', 'metrics', 'topk', 'valid_metric', 'valid_metric_bigger', 'eval_batch_size', 'metric_decimal_place'], 'Dataset': ['field_separator', 'seq_separator', 'USER_ID_FIELD', 'ITEM_ID_FIELD', 'RATING_FIELD', 'TIME_FIELD', 'seq_len', 'LABEL_FIELD', 'threshold', 'NEG_PREFIX', 'ITEM_LIST_LENGTH_FIELD', 'LIST_SUFFIX', 'MAX_ITEM_LIST_LENGTH', 'POSITION_FIELD', 'HEAD_ENTITY_ID_FIELD', 'TAIL_ENTITY_ID_FIELD', 'RELATION_ID_FIELD', 'ENTITY_ID_FIELD', 'load_col', 'unload_col', 'unused_col', 'additional_feat_suffix', 'filter_inter_by_user_or_item', 'rm_dup_inter', 'val_interval', 'user_inter_num_interval', 'item_inter_num_interval', 'alias_of_user_id', 'alias_of_item_id', 'alias_of_entity_id', 'alias_of_relation_id', 'preload_weight', 'normalize_field', 'normalize_all']}
yaml_loader = <class 'yaml.loader.FullLoader'>
file_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': './recbole/data/dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'additional_feat_suffix': ['image'], 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'image': ['img_id', 'img_emb']}, 'alias_of_item_id': ['img_id'], 'preload_weight': {'img_id': 'img_emb'}, 'MAX_ITEM_LIST_LENGTH': 50, 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'orig_attribute_hidden_size': [128], 'attribute_hidden_size': [128], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['img_emb'], 'feature_type': ['static'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5], 'attribute_predictor': ['cos_sim'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'images_obrazek', 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'neg_sampling': None, 'annealing': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 256, 'loss_decimal_place': 4, 'metric_decimal_place': 4}
variable_config_dict = {'neg_sampling': None}
cmd_config_dict = {'gpu_id': 0, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors(image).yaml'}
external_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': './recbole/data/dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'additional_feat_suffix': ['image'], 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'image': ['img_id', 'img_emb']}, 'alias_of_item_id': ['img_id'], 'preload_weight': {'img_id': 'img_emb'}, 'MAX_ITEM_LIST_LENGTH': 50, 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'orig_attribute_hidden_size': [128], 'attribute_hidden_size': [128], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['img_emb'], 'feature_type': ['static'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5], 'attribute_predictor': ['cos_sim'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'images_obrazek', 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'neg_sampling': None, 'annealing': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 256, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors(image).yaml'}
model = SASRecD
model_class = <class 'recbole.model.sequential_recommender.sasrecd.SASRecD'>
dataset = Amazon_Sports_and_Outdoors
internal_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 2020, 'state': 'INFO', 'reproducibility': True, 'data_path': 'dataset/', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'epochs': 300, 'train_batch_size': 2048, 'learner': 'adam', 'learning_rate': 0.001, 'neg_sampling': {'uniform': 1}, 'eval_step': 1, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'multi_gpus': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision'], 'topk': [10], 'valid_metric': 'MRR@10', 'valid_metric_bigger': True, 'eval_batch_size': 4096, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'n_layers': 4, 'n_heads': 2, 'hidden_size': 256, 'attribute_hidden_size': [64], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['class'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'concat', 'lamdas': [10], 'attribute_predictor': 'linear', 'field_separator': '\t', 'seq_separator': ' ', 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'seq_len': None, 'LABEL_FIELD': 'label', 'threshold': None, 'NEG_PREFIX': 'neg_', 'load_col': {'inter': ['user_id', 'item_id']}, 'unload_col': None, 'unused_col': None, 'additional_feat_suffix': None, 'rm_dup_inter': None, 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[0,inf)', 'item_inter_num_interval': '[0,inf)', 'alias_of_user_id': None, 'alias_of_item_id': None, 'alias_of_entity_id': None, 'alias_of_relation_id': None, 'preload_weight': None, 'normalize_field': None, 'normalize_all': None, 'ITEM_LIST_LENGTH_FIELD': 'item_length', 'LIST_SUFFIX': '_list', 'MAX_ITEM_LIST_LENGTH': 50, 'POSITION_FIELD': 'position_id', 'HEAD_ENTITY_ID_FIELD': 'head_id', 'TAIL_ENTITY_ID_FIELD': 'tail_id', 'RELATION_ID_FIELD': 'relation_id', 'ENTITY_ID_FIELD': 'entity_id', 'benchmark_filename': None, 'MODEL_TYPE': <ModelType.SEQUENTIAL: 2>}
final_config_dict = {'gpu_id': 0, 'use_gpu': True, 'seed': 212, 'state': 'INFO', 'reproducibility': True, 'data_path': '\\\\wsl.localhost\\Ubuntu\\home\\piotrs\\Uni\\SequentialRecommendation\\recbole\\data\\dataset\\Amazon_Sports_and_Outdoors', 'checkpoint_dir': 'saved', 'show_progress': True, 'save_dataset': False, 'save_dataloaders': False, 'epochs': 200, 'train_batch_size': 1024, 'learner': 'adam', 'learning_rate': 0.0001, 'neg_sampling': None, 'eval_step': 2, 'stopping_step': 10, 'clip_grad_norm': None, 'weight_decay': 0.0, 'multi_gpus': False, 'eval_args': {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}, 'repeatable': True, 'metrics': ['Recall', 'NDCG'], 'topk': [3, 5, 10, 20], 'valid_metric': 'Recall@10', 'valid_metric_bigger': True, 'eval_batch_size': 1, 'loss_decimal_place': 4, 'metric_decimal_place': 4, 'n_layers': 3, 'n_heads': 8, 'hidden_size': 256, 'attribute_hidden_size': [128], 'inner_size': 256, 'hidden_dropout_prob': 0.5, 'attn_dropout_prob': 0.3, 'hidden_act': 'gelu', 'layer_norm_eps': 1e-12, 'initializer_range': 0.02, 'selected_features': ['img_emb'], 'pooling_mode': 'sum', 'loss_type': 'CE', 'weight_sharing': 'not', 'fusion_type': 'gate', 'lamdas': [5], 'attribute_predictor': ['cos_sim'], 'field_separator': '\t', 'seq_separator': ' ', 'USER_ID_FIELD': 'user_id', 'ITEM_ID_FIELD': 'item_id', 'RATING_FIELD': 'rating', 'TIME_FIELD': 'timestamp', 'seq_len': None, 'LABEL_FIELD': 'label', 'threshold': None, 'NEG_PREFIX': 'neg_', 'load_col': {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'image': ['img_id', 'img_emb']}, 'unload_col': None, 'unused_col': None, 'additional_feat_suffix': ['image'], 'rm_dup_inter': None, 'val_interval': None, 'filter_inter_by_user_or_item': True, 'user_inter_num_interval': '[5,inf)', 'item_inter_num_interval': '[5,inf)', 'alias_of_user_id': None, 'alias_of_item_id': ['img_id'], 'alias_of_entity_id': None, 'alias_of_relation_id': None, 'preload_weight': {'img_id': 'img_emb'}, 'normalize_field': None, 'normalize_all': None, 'ITEM_LIST_LENGTH_FIELD': 'item_length', 'LIST_SUFFIX': '_list', 'MAX_ITEM_LIST_LENGTH': 50, 'POSITION_FIELD': 'position_id', 'HEAD_ENTITY_ID_FIELD': 'head_id', 'TAIL_ENTITY_ID_FIELD': 'tail_id', 'RELATION_ID_FIELD': 'relation_id', 'ENTITY_ID_FIELD': 'entity_id', 'benchmark_filename': None, 'MODEL_TYPE': <ModelType.SEQUENTIAL: 2>, 'orig_attribute_hidden_size': [420, 420], 'feature_type': ['static'], 'diffusion': {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}, 'lambda': 0.5, 'wandb_run_name': 'test_run', 'annealing': False, 'model': 'SASRecD', 'dataset': 'Amazon_Sports_and_Outdoors', 'config_files': 'configs/Amazon_Sports_and_Outdoors(image).yaml', 'MODEL_INPUT_TYPE': <InputType.POINTWISE: 1>, 'eval_type': <EvaluatorType.RANKING: 1>, 'device': 'cpu', 'train_neg_sample_args': {'strategy': 'none'}, 'eval_neg_sample_args': {'strategy': 'full', 'distribution': 'uniform'}}

25 Jan 20:15    INFO
General Hyper Parameters:
gpu_id = 0
use_gpu = True
seed = 212
state = INFO
reproducibility = True
data_path = \\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\Amazon_Sports_and_Outdoors
show_progress = True
save_dataset = False
save_dataloaders = False
benchmark_filename = None

Training Hyper Parameters:
checkpoint_dir = saved
epochs = 200
train_batch_size = 1024
learner = adam
learning_rate = 0.0001
eval_step = 2
stopping_step = 10
clip_grad_norm = None
weight_decay = 0.0
loss_decimal_place = 4

Evaluation Hyper Parameters:
eval_args = {'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}
metrics = ['Recall', 'NDCG']
topk = [3, 5, 10, 20]
valid_metric = Recall@10
valid_metric_bigger = True
eval_batch_size = 1
metric_decimal_place = 4

Dataset Hyper Parameters:
field_separator =
seq_separator =
USER_ID_FIELD = user_id
ITEM_ID_FIELD = item_id
RATING_FIELD = rating
TIME_FIELD = timestamp
seq_len = None
LABEL_FIELD = label
threshold = None
NEG_PREFIX = neg_
load_col = {'inter': ['user_id', 'item_id', 'rating', 'timestamp'], 'item': ['item_id', 'title', 'sales_rank', 'price', 'brand', 'categories', 'sales_type'], 'image': ['img_id', 'img_emb']}
unload_col = None
unused_col = None
additional_feat_suffix = ['image']
rm_dup_inter = None
val_interval = None
filter_inter_by_user_or_item = True
user_inter_num_interval = [5,inf)
item_inter_num_interval = [5,inf)
alias_of_user_id = None
alias_of_item_id = ['img_id']
alias_of_entity_id = None
alias_of_relation_id = None
preload_weight = {'img_id': 'img_emb'}
normalize_field = None
normalize_all = None
ITEM_LIST_LENGTH_FIELD = item_length
LIST_SUFFIX = _list
MAX_ITEM_LIST_LENGTH = 50
POSITION_FIELD = position_id
HEAD_ENTITY_ID_FIELD = head_id
TAIL_ENTITY_ID_FIELD = tail_id
RELATION_ID_FIELD = relation_id
ENTITY_ID_FIELD = entity_id

Other Hyper Parameters:
neg_sampling = None
multi_gpus = False
repeatable = True
n_layers = 3
n_heads = 8
hidden_size = 256
attribute_hidden_size = [128]
inner_size = 256
hidden_dropout_prob = 0.5
attn_dropout_prob = 0.3
hidden_act = gelu
layer_norm_eps = 1e-12
initializer_range = 0.02
selected_features = ['img_emb']
pooling_mode = sum
loss_type = CE
weight_sharing = not
fusion_type = gate
lamdas = [5]
attribute_predictor = ['cos_sim']
MODEL_TYPE = ModelType.SEQUENTIAL
orig_attribute_hidden_size = [420, 420]
feature_type = ['static']
diffusion = {'device': 'cuda', 'dims': [1000], 'emb_size': 20, 'mean_type': 'x0', 'noise_max': 0.02, 'noise_min': 0.0001, 'noise_scale': 0.1, 'noise_schedule': 'linear-var', 'norm': False, 'num_heads': 4, 'reweight': True, 'sampling_noise': False, 'sampling_steps': 0, 'steps': 5, 'structure': 'MLP', 'time_type': 'cat', 'hiddenSize': 128, 'inputSize': 128}
lambda = 0.5
wandb_run_name = test_run
annealing = False
MODEL_INPUT_TYPE = InputType.POINTWISE
eval_type = EvaluatorType.RANKING
device = cpu
train_neg_sample_args = {'strategy': 'none'}
eval_neg_sample_args = {'strategy': 'full', 'distribution': 'uniform'}


\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:446: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].fillna(value='', inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:446: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[field].fillna(value='', inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:965: FutureWarning: using <built-in function len> in Series.agg cannot aggregate and has been deprecated. Use Series.transform to keep behavior unchanged.
  split_point = np.cumsum(feat[field].agg(len))[:-1]
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:568: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=0, inplace=True)
\\wsl.localhost\Ubuntu\home\piotrs\Uni\SequentialRecommendation\recbole\data\dataset\dataset.py:570: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  feat[field].fillna(value=feat[field].mean(), inplace=True)
25 Jan 20:15    INFO  Amazon_Sports_and_Outdoors
The number of users: 35599
Average actions of users: 8.324540704533963
The number of items: 18358
Average actions of items: 16.142997221768262
The number of inters: 296337
The sparsity of the dataset: 99.95465569853714%
Remain Fields: ['user_id', 'item_id', 'rating', 'timestamp', 'title', 'price', 'brand', 'categories', 'sales_type', 'sales_rank', 'img_id', 'img_emb']
25 Jan 20:16    INFO  [Training]: train_batch_size = [1024] negative sampling: [None]
25 Jan 20:16    INFO  [Evaluation]: eval_batch_size = [1] eval_args: [{'split': {'LS': 'valid_and_test'}, 'group_by': 'user', 'order': 'TO', 'mode': 'full'}]
25 Jan 20:16    INFO  SASRecD(
  (item_embedding): Embedding(18358, 256, padding_idx=0)
  (position_embedding): Embedding(50, 256)
  (feature_embed_layer_list): ModuleList(
    (0): Embedding(18358, 128)
  )
  (trm_encoder): DIFTransformerEncoder(
    (layer): ModuleList(
      (0-2): 3 x DIFTransformerLayer(
        (multi_head_attention): DIFMultiHeadAttention(
          (query): Linear(in_features=256, out_features=256, bias=True)
          (key): Linear(in_features=256, out_features=256, bias=True)
          (value): Linear(in_features=256, out_features=256, bias=True)
          (query_p): Linear(in_features=256, out_features=256, bias=True)
          (key_p): Linear(in_features=256, out_features=256, bias=True)
          (query_layers): ModuleList(
            (0): Linear(in_features=128, out_features=128, bias=True)
          )
          (key_layers): ModuleList(
            (0): Linear(in_features=128, out_features=128, bias=True)
          )
          (fusion_layer): VanillaAttention(
            (projection): Sequential(
              (0): Linear(in_features=50, out_features=50, bias=True)
              (1): ReLU(inplace=True)
              (2): Linear(in_features=50, out_features=1, bias=True)
            )
          )
          (attn_dropout): Dropout(p=0.3, inplace=False)
          (dense): Linear(in_features=256, out_features=256, bias=True)
          (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (out_dropout): Dropout(p=0.5, inplace=False)
        )
        (feed_forward): FeedForward(
          (dense_1): Linear(in_features=256, out_features=256, bias=True)
          (dense_2): Linear(in_features=256, out_features=256, bias=True)
          (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.5, inplace=False)
        )
      )
    )
  )
  (ap): ModuleList(
    (0): Linear(in_features=256, out_features=128, bias=True)
  )
  (LayerNorm): LayerNorm((256,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.5, inplace=False)
  (loss_fct): CrossEntropyLoss()
  (attribute_loss_fct): BCEWithLogitsLoss()
)
Trainable parameters: 6434811

In [4]:
def predict_item(inp_model, inp_interaction):
    item_seq = inp_interaction[inp_model.ITEM_SEQ]
    item_seq_len = inp_interaction[inp_model.ITEM_SEQ_LEN]

    seq_output = inp_model.forward(item_seq, item_seq_len)

    test_items_emb = inp_model.item_embedding.weight
    scores = torch.matmul(seq_output, test_items_emb.transpose(0, 1))

    idx = torch.argmax(scores, dim=1)

    return idx

### Import mappings

In [5]:
df_items = pd.read_csv('../../Amazon_Sports_and_Outdoors/Amazon_Sports_and_Outdoors.item', sep='\t')
df_items.head(5)

,item_id:token,title:token,price:float,brand:token,categories:token_seq,sales_type:token,sales_rank:float
0,0,Ghost Inc Glock Armorers Tool 3/32 Punch,9.99,Ghost,"'Sports & Outdoors', 'Hunting', 'Hunting & Fis...",Sports &amp; Outdoors,532941.0
1,1,5 LED Bicycle Rear Tail Red Bike Torch Laser B...,8.26,NaN,"'Lights & Reflectors', 'Sports & Outdoors', 'C...",Toys & Games,15617.0
2,3,Black Mountain Products Resistance Band Set wi...,32.99,Black Mountain,"'Accessories', 'Exercise Bands', 'Sports & Out...",Sports &amp; Outdoors,1010.0
3,2,Black Mountain Products Single Resistance Band...,10.49,Black Mountain,"'Accessories', 'Exercise Bands', 'Sports & Out...",Sports &amp; Outdoors,1010.0
4,4,Outers Universal 32-Piece Blow Molded Gun Clea...,21.99,Outers,"'Sports & Outdoors', 'Hunting', 'Gun Cleaning ...",Sports &amp; Outdoors,26457.0

In [6]:
data = []
with open('../../Amazon_Sports_and_Outdoors/meta_Sports_and_Outdoors.json', 'r', encoding='utf-8') as f:
    for line in f:
        line = line.strip()
        if line:
            data.append(ast.literal_eval(line))  # safe Python dict parser

df_meta = pd.DataFrame(data)
df_meta.head(5)

,asin,title,price,imUrl,related,brand,categories,salesRank,description
0,0000032069,Adult Ballet Tutu Cheetah Pink,7.89,http://ecx.images-amazon.com/images/I/51EzU6qu...,"{'also_bought': ['0000032050', 'B00D0DJAEG', '...",BubuBibi,"[[Sports & Outdoors, Other Sports, Dance, Clot...",NaN,NaN
1,0000031909,Girls Ballet Tutu Neon Pink,7.00,http://ecx.images-amazon.com/images/I/41xBoP0F...,"{'also_bought': ['B002BZX8Z6', 'B00JHONN1S', '...",Unknown,"[[Sports & Outdoors, Other Sports, Dance]]",{'Toys & Games': 201847},High quality 3 layer ballet tutu. 12 inches in...
2,0000032034,Adult Ballet Tutu Yellow,7.87,http://ecx.images-amazon.com/images/I/21GNUNIa...,"{'also_bought': ['B00D2JSRFQ', '0000032042', '...",BubuBibi,"[[Sports & Outdoors, Other Sports, Dance, Clot...",NaN,NaN
3,0000031852,Girls Ballet Tutu Zebra Hot Pink,3.17,http://ecx.images-amazon.com/images/I/51fAmVkT...,"{'also_bought': ['B00JHONN1S', 'B002BZX8Z6', '...",Coxlures,"[[Sports & Outdoors, Other Sports, Dance]]",{'Toys & Games': 211836},TUtu
4,0000032050,Adult Ballet Tutu Purple,12.85,http://ecx.images-amazon.com/images/I/41TxNYG8...,"{'also_bought': ['B00D2JSRFQ', 'B00D2JTMS2', '...",BubuBibi,"[[Sports & Outdoors, Other Sports, Dance, Clot...",NaN,NaN

In [7]:
with open('../../Amazon_Sports_and_Outdoors/item_mapping_Amazon_Sports_and_Outdoors.json', 'r') as f:
    item_mapping = json.load(f)

print(item_mapping[:10])

['1881509818', '2094869245', '7245456259', '7245456313', 'B000002NUS', 'B00000ELZ5', 'B00000IURU', 'B00000IUX5', 'B00000J6JO', 'B0000224UE']

In [12]:
pd.set_option('display.max_colwidth', None)

for interaction, _, _, _ in test_data:
    asins = set()
    for model in models:
        index = predict_item(model, interaction)
        index = index[0].item()
        asin = item_mapping[index]

        asins.add(asin)

    if len(asins) != len(models):
        continue

    print("-------- GROUND-TRUTH --------")
    pos_item = interaction[models[0].POS_ITEM_ID].item()
    asin = item_mapping[pos_item]
    row = df_meta[df_meta["asin"] == asin]

    title = row["title"].item()
    categories = row["categories"].item()
    imUrl = row["imUrl"].item()

    print(f'Title: {title} \n Categories: {categories} \n imUrl: {imUrl}')

    for i, model in enumerate(models):
        print(f"-------- PREDICTION {i} --------")
        index = predict_item(model, interaction)
        index = index[0].item()
        asin = item_mapping[index]

        row = df_meta[df_meta["asin"] == asin]

        title = row["title"].item()
        categories = row["categories"].item()
        imUrl = row["imUrl"].item()

        print(f'Title: {title} \n Categories: {categories} \n imUrl: {imUrl}')

-------- GROUND-TRUTH --------
Title: Pedro's Universal Bicycle Crank Remover with Handle
 Categories: [['Sports & Outdoors', 'Cycling', 'Bike Tools & Maintenance', 'Shop Tools']]
 imUrl: http://ecx.images-amazon.com/images/I/31Z25FD60EL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Park Tool Spoke Wrench SW-0 Through SW-3
 Categories: [['Sports & Outdoors', 'Cycling', 'Bike Tools & Maintenance', 'Shop Tools']]
 imUrl: http://ecx.images-amazon.com/images/I/31bu1jfVQxL._SY300_.jpg
-------- PREDICTION 1 --------
Title: Sawyer Products PointOne Squeeze Water Filtration System
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Hydration', 'Water Filters']]
 imUrl: http://ecx.images-amazon.com/images/I/51SJ5lM%2BhyL._SY300_.jpg
-------- PREDICTION 2 --------
Title: Pearl iZUMi Men's Quest Cycling Bib Short,Black,X-Large
 Categories: [['Sports & Outdoors', 'Clothing', 'Men', 'Shorts', 'Compression Shorts']]
 imUrl: http://ecx.images-amazon.com/images/I/315SfZuahML._SY300_.jpg
-------- GROUND-TRUTH --------
Title: UTG Pro Tactical QD Low-Profile Rail System
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Night Vision']]
 imUrl: http://ecx.images-amazon.com/images/I/31CwA4fx5BL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Butler Creek LULA All-in-One Magazine Speed Loader and Unloader 223 Remington 5.56mm NATO
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Accessories', 'Magazine Loaders']]
 imUrl: http://ecx.images-amazon.com/images/I/419NdR8A-RL._SX300_.jpg
-------- PREDICTION 1 --------
Title: Butler Creek Lula Universal Pistol Magazine Loader
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Accessories', 'Magazine Loaders']]
 imUrl: http://ecx.images-amazon.com/images/I/31gyd1PYsfL._SX300_.jpg
-------- PREDICTION 2 --------
Title: GunVault NV100 NanoVault with Key Lock, Fits Sub-Compact Pistols
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Storage & Safes', 'Gun Safes & Cabinets']]
 imUrl: http://ecx.images-amazon.com/images/I/51DDE4BNp4L._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Burris 410348 AR-F3 Fastfire Flattop Mount (Black)
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Accessories', 'Trophy Mounts']]
 imUrl: http://ecx.images-amazon.com/images/I/414msBlQDJL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Dreamie Fleece Camping Blanket With Travel Bag - Dreamie Z-00204
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Camp Bedding', 'Blankets']]
 imUrl: http://ecx.images-amazon.com/images/I/51FMuYOTU8L._SX300_.jpg
-------- PREDICTION 1 --------
Title: Smith &amp; Wesson 1911 Tactical Bag
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Holsters, Cases & Bags', 'Gun Holsters']]
 imUrl: http://ecx.images-amazon.com/images/I/51n8mGte6BL._SY300_.jpg
-------- PREDICTION 2 --------
Title: Coleman Road Trip Cast-Iron Griddle
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Camp Kitchen', 'Pots & Pans']]
 imUrl: http://ecx.images-amazon.com/images/I/414N21NDKWL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Paracord Planet 1/8&quot; Shock Cord in Various Colors - Choose from 10, 25, 50, and 100 Feet, Made in USA
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Tactical & Duty', 'Paracords']]
 imUrl: http://ecx.images-amazon.com/images/I/61ZhR1KtllL._SY300_.jpg
-------- PREDICTION 0 --------
Title: HDE&reg; Tactical Red Dot Laser Sight for Pistol/Handgun Picatinny Rail Mount (Perfect for Hunting)
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Gun Sights']]
 imUrl: http://ecx.images-amazon.com/images/I/41ew0q3rjuL._SY300_.jpg
-------- PREDICTION 1 --------
Title: Etekcity&reg; Portable Outdoor Picnic Backpacking Canister Camp Stove with Carry Case/ Adjustable Fire/ Steel Stand, Only 7.9oz
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Camp Kitchen', 'Camp Stoves']]
 imUrl: http://ecx.images-amazon.com/images/I/41OfjUZbn4L._SY300_.jpg
-------- PREDICTION 2 --------
Title: Bicycle Adjustable Aluminium Alloy Bike Bicycle Kickstand Side Kickstand Fit for 20&quot; 24&quot; 26&quot;- Black
 Categories: [['Sports & Outdoors', 'Cycling', 'Bike Racks & Bags', 'Cargo Racks']]
 imUrl: http://ecx.images-amazon.com/images/I/51jeqL9sAlL._SY300_.jpg
-------- GROUND-TRUTH --------
Title: Magnum Compact Rescue Knife
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Tactical & Duty', 'Tactical Knives']]
 imUrl: http://ecx.images-amazon.com/images/I/31J%2BT7DO4UL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Butler Creek LULA All-in-One Magazine Speed Loader and Unloader 223 Remington 5.56mm NATO
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Accessories', 'Magazine Loaders']]
 imUrl: http://ecx.images-amazon.com/images/I/419NdR8A-RL._SX300_.jpg
-------- PREDICTION 1 --------
Title: KMC Z410 Bicycle Chain (1-Speed, 1/2 x 1/8-Inch, 112L)
 Categories: [['Sports & Outdoors', 'Cycling', 'Parts & Components', 'Drivetrain Components', 'Chains']]
 imUrl: http://ecx.images-amazon.com/images/I/419zeASGz8L._SY300_.jpg
-------- PREDICTION 2 --------
Title: Klean Kanteen 27 oz. Sling
 Categories: [['Sports & Outdoors', 'Accessories', 'Sports Water Bottles']]
 imUrl: http://ecx.images-amazon.com/images/I/41oW-nHJfCL._SY300_.jpg
-------- GROUND-TRUTH --------
Title: KNS Push Button Rear Take Down Pin, .250-Diameter, Black
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Maintenance', 'Gunsmithing Tools']]
 imUrl: http://ecx.images-amazon.com/images/I/31YOS3SS3RL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Blackhawk Black Shotgun Sling
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Holsters, Cases & Bags', 'Gun Slings']]
 imUrl: http://ecx.images-amazon.com/images/I/41tOeTrZvhL._SX300_.jpg
-------- PREDICTION 1 --------
Title: UTG 2nd Gen HK STANAG Steel Claw Mount
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Night Vision']]
 imUrl: http://ecx.images-amazon.com/images/I/41Z4ufo1b0L._SX300_.jpg
-------- PREDICTION 2 --------
Title: .30-30 Winchester 7.62x51mmR Caliber Cartridge Laser Bore Sighter Boresighter
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Boresighters']]
 imUrl: http://ecx.images-amazon.com/images/I/31U8hoaE8YL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Victorinox SwissCard
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Knives & Tools', 'Folding Knives']]
 imUrl: http://ecx.images-amazon.com/images/I/418EAUS1lVL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Pflueger President Spinning Reel, 115-Yards/6-Pound
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Fishing', 'Reels', 'Spinning Reels']]
 imUrl: http://ecx.images-amazon.com/images/I/51YTplvZ8oL._SY300_.jpg
-------- PREDICTION 1 --------
Title: NALGENE Tritan 1-Quart Narrow Mouth BPA-Free Water Bottle
 Categories: [['Sports & Outdoors', 'Accessories', 'Sports Water Bottles']]
 imUrl: http://ecx.images-amazon.com/images/I/41awXZsDLHL._SY300_.jpg
-------- PREDICTION 2 --------
Title: Otis Professional Pistol Cleaning System
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Maintenance', 'Gun Cleaning Kits']]
 imUrl: http://ecx.images-amazon.com/images/I/410xcBN404L._SX300_.jpg
-------- GROUND-TRUTH --------
Title: SEAL Pup with Nylon Sheath in Clam
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Airsoft, Air Guns & Slingshots', 'Air Guns']]
 imUrl: http://ecx.images-amazon.com/images/I/31NsDSAZcrL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Russell Athletic Men's Basic Cotton Tee
 Categories: [['Sports & Outdoors', 'Clothing'], ['Clothing, Shoes & Jewelry', 'Men', 'Clothing', 'Active', 'Active Shirts & Tees'], ['Clothing, Shoes & Jewelry', 'Men', 'Big & Tall']]
 imUrl: http://ecx.images-amazon.com/images/I/41vWP8wEmIL._SX342_.jpg
-------- PREDICTION 1 --------
Title: MTECH USA Xtreme MX-8059 Series Tactical Fixed Blade Knife 9-Inch Overall
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Tactical & Duty', 'Tactical Knives']]
 imUrl: http://ecx.images-amazon.com/images/I/31q0IKTJ7fL._SX300_.jpg
-------- PREDICTION 2 --------
Title: OD Trifold Medical Bag - (without contents)
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Tactical & Duty', 'Tactical Bags & Packs', 'Tactical Backpacks']]
 imUrl: http://ecx.images-amazon.com/images/I/41sJYdFa0QL._SY300_.jpg
-------- GROUND-TRUTH --------
Title: ProSource Ultra Deluxe Revolutionary Sports Medicine Roller
 Categories: [['Sports & Outdoors', 'Exercise & Fitness', 'Balance Trainers', 'Foam Rollers']]
 imUrl: http://ecx.images-amazon.com/images/I/41ti-iwT-dL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Predator Blowgun Spike Darts.
 Categories: [['Sports & Outdoors', 'Other Sports', 'Martial Arts', 'Weapons', 'Ninja Weapons']]
 imUrl: http://ecx.images-amazon.com/images/I/51sN9%2BIPA3L._SX300_.jpg
-------- PREDICTION 1 --------
Title: Northstar Tactical Shotgun Ammo Pouch
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Storage & Safes', 'Ammunition & Magazine Pouches']]
 imUrl: http://ecx.images-amazon.com/images/I/51OMqUlDhQL._SX300_.jpg
-------- PREDICTION 2 --------
Title: terriFIT Ultra Speed Cable Jump Rope || 10 or 11 FT || Free EXTRA Cable - 60-Day Money Back Guarantee - Best for CrossFit WODs and Advanced Jumping - Adjustable length - FREE 'How To Improve Your DUs' Manual
 Categories: [['Sports & Outdoors', 'Exercise & Fitness', 'Accessories', 'Jump Ropes']]
 imUrl: http://ecx.images-amazon.com/images/I/51VWxf8-ZCL._SY300_.jpg
-------- GROUND-TRUTH --------
Title: Champion Favorite Bermuda Short
 Categories: [['Sports & Outdoors', 'Clothing', 'Women', 'Shorts'], ['Clothing, Shoes & Jewelry', 'Women', 'Clothing', 'Active', 'Active Shorts']]
 imUrl: http://ecx.images-amazon.com/images/I/31rM2XFsz-L._SX342_.jpg
-------- PREDICTION 0 --------
Title: Champion Mens Jersey Ringer Tee
 Categories: [['Sports & Outdoors', 'Clothing', 'Men', 'Shirts', 'T-Shirts'], ['Clothing, Shoes & Jewelry', 'Men', 'Clothing', 'Active', 'Active Shirts & Tees'], ['Clothing, Shoes & Jewelry', 'Men', 'Clothing', 'Shirts'], ['Clothing, Shoes & Jewelry', 'Novelty, Costumes & More', 'Band & Music Fan', 'T-Shirts']]
 imUrl: http://ecx.images-amazon.com/images/I/416jUnsTYfL._SX342_.jpg
-------- PREDICTION 1 --------
Title: Pearl Izumi Women's Select Glove
 Categories: [['Sports & Outdoors', 'Cycling', 'Clothing', 'Women', 'Gloves']]
 imUrl: http://ecx.images-amazon.com/images/I/41zyxvWq73L._SY300_.jpg
-------- PREDICTION 2 --------
Title: Tops M4X Punisher 13 1/2&quot; overall 8 1/2&quot; 1095 high carbon steel sawback blade wi
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Tactical & Duty', 'Tactical Knives']]
 imUrl: http://ecx.images-amazon.com/images/I/21DW93RnstL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Crosman Competition .177 Cal, 7.4 Grains, Wadcutter, 500ct
 Categories: [['Sports & Outdoors', 'Paintball & Airsoft', 'Airsoft', 'BBs']]
 imUrl: http://ecx.images-amazon.com/images/I/51giLrJcjPL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Theo Klein Toy Swiss Army Knife
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Knives & Tools', 'Folding Knives']]
 imUrl: http://ecx.images-amazon.com/images/I/418a-QHQvIL._SX300_.jpg
-------- PREDICTION 1 --------
Title: O'Neill Epic II 3/2 CT (Black)
 Categories: [['Sports & Outdoors', 'Boating & Water Sports', 'Surfing', 'Wetsuits']]
 imUrl: http://ecx.images-amazon.com/images/I/31xRHjmwcfL._SY300_.jpg
-------- PREDICTION 2 --------
Title: UTG Elite Tactical Right Handed Leg Holster
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Holsters, Cases & Bags', 'Gun Holsters']]
 imUrl: http://ecx.images-amazon.com/images/I/41JpnkXvi-L._SY300_.jpg
-------- GROUND-TRUTH --------
Title: Stansport Hurricane High Oil Lantern (Red, 12-Inch)
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Lights & Lanterns', 'Lanterns']]
 imUrl: http://ecx.images-amazon.com/images/I/41eesrf8etL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Super Turbo 800watt Elite 36v Electric Scooter &quot;Black&quot; (Now includes Econo/Turbo mode button!)
 Categories: [['Sports & Outdoors', 'Action Sports', 'Scooters & Equipment', 'Scooters']]
 imUrl: http://ecx.images-amazon.com/images/I/41mG5GKo2KL._SY300_.jpg
-------- PREDICTION 1 --------
Title: Texsport Campfire Tripod
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Camp Kitchen', 'Campfire Cookware']]
 imUrl: http://ecx.images-amazon.com/images/I/41yINz3BMmL._SY300_.jpg
-------- PREDICTION 2 --------
Title: Butler Creek LULA All-in-One Magazine Speed Loader and Unloader 223 Remington 5.56mm NATO
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Accessories', 'Magazine Loaders']]
 imUrl: http://ecx.images-amazon.com/images/I/419NdR8A-RL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: RCBS 20515 Carbide Die Set, 9MMLUGER/9x21/9x23
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Maintenance', 'Gunsmithing Tools']]
 imUrl: http://ecx.images-amazon.com/images/I/31GzknnaFSL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Speedo Women's ZipWalker Water Shoe
 Categories: [['Sports & Outdoors', 'Boating & Water Sports', 'Swimming'], ['Clothing, Shoes & Jewelry', 'Shoes & Accessories: International Shipping Available'], ['Clothing, Shoes & Jewelry', 'S', 'Speedo'], ['Clothing, Shoes & Jewelry', 'Women', 'Shoes', 'Athletic', 'Water Shoes']]
 imUrl: http://ecx.images-amazon.com/images/I/41qMuxbfglL._SX395_.jpg
-------- PREDICTION 1 --------
Title: Century 14,000 BTU Infrared Heater
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Safety & Survival', 'Emergency Warmers']]
 imUrl: http://ecx.images-amazon.com/images/I/41BHTGZV9XL._SY300_.jpg
-------- PREDICTION 2 --------
Title: Rothco Type III 550-Pound Commercial Paracord
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Tactical & Duty', 'Paracords']]
 imUrl: http://ecx.images-amazon.com/images/I/41MF5Vhnf2L._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Crosman Remington Vantage .177 Caliber Hardwood Stock Break Barrel Air Rifle with 4 X 32mm Scope
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Airsoft, Air Guns & Slingshots', 'Air Guns', 'Air Rifles']]
 imUrl: http://ecx.images-amazon.com/images/I/21IQV%2BKMTPL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Fobus Standard Holster RH Paddle SWMP S&amp;W M&amp;P 9mm, .40, .45 (compact &amp; full size), SD 9 &amp;40
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Holsters, Cases & Bags', 'Gun Holsters']]
 imUrl: http://ecx.images-amazon.com/images/I/41kUbs19opL._SY300_.jpg
-------- PREDICTION 1 --------
Title: Crosman Stinger P311 Airsoft Pistol (Black)
 Categories: [['Sports & Outdoors', 'Paintball & Airsoft', 'Airsoft', 'Guns & Rifles', 'Pistols']]
 imUrl: http://ecx.images-amazon.com/images/I/41a1sJyUzJL._SX300_.jpg
-------- PREDICTION 2 --------
Title: Acczilla Stainless Steel Travel Hike Folding Collapsible 5 Ounce Cup With Key Ring
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Camp Kitchen', 'Dishes & Utensils', 'Cups & Mugs']]
 imUrl: http://ecx.images-amazon.com/images/I/41A-4OnlYQL._SY300_.jpg
-------- GROUND-TRUTH --------
Title: Dakine Men's Scout Glove
 Categories: [['Sports & Outdoors', 'Clothing', 'Men', 'Accessories', 'Gloves, Mittens & Liners', 'Gloves']]
 imUrl: http://ecx.images-amazon.com/images/I/41bJ%2B1FkE1L._SY300_.jpg
-------- PREDICTION 0 --------
Title: Caldwell The Stable Table Carry Bag
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Accessories', 'Targets & Accessories']]
 imUrl: http://ecx.images-amazon.com/images/I/41vTXFY2oML._SY300_.jpg
-------- PREDICTION 1 --------
Title: Level III Lv3 Molle Assault Pack Backpack--ACU
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Backpacks & Bags', 'Hiking Daypacks']]
 imUrl: http://ecx.images-amazon.com/images/I/51U--opBA%2BL._SY300_.jpg
-------- PREDICTION 2 --------
Title: .30-30 Winchester 7.62x51mmR Caliber Cartridge Laser Bore Sighter Boresighter
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Boresighters']]
 imUrl: http://ecx.images-amazon.com/images/I/31U8hoaE8YL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Avenir Thorn-Resistant Schrader Valve Tube (16 x 1.75-2.125)
 Categories: [['Sports & Outdoors', 'Cycling', 'Tires & Tubes', 'Tubes']]
 imUrl: http://ecx.images-amazon.com/images/I/417ir0x02KL._SX300_.jpg
-------- PREDICTION 0 --------
Title: 3Skull Paintball Tippmann A-5/X7 450 Rd Cyclone Offset Hopper - Black
 Categories: [['Sports & Outdoors', 'Paintball & Airsoft', 'Paintball', 'Loaders & Accessories', 'Loaders']]
 imUrl: http://ecx.images-amazon.com/images/I/41uGKd1v7sL._SY300_.jpg
-------- PREDICTION 1 --------
Title: KMC Z410 Bicycle Chain (1-Speed, 1/2 x 1/8-Inch, 112L)
 Categories: [['Sports & Outdoors', 'Cycling', 'Parts & Components', 'Drivetrain Components', 'Chains']]
 imUrl: http://ecx.images-amazon.com/images/I/419zeASGz8L._SY300_.jpg
-------- PREDICTION 2 --------
Title: Blackburn Mars Click
 Categories: [['Sports & Outdoors', 'Cycling', 'Lights & Reflectors', 'Headlight-Taillight Combinations']]
 imUrl: http://ecx.images-amazon.com/images/I/41ncVk2WugL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: Bundle - 2 Items: UCO Match Container Kit with 75 UCO Stormproof Matches - Waterproof &amp; Windproof
 Categories: [['Sports & Outdoors', 'Outdoor Gear', 'Camping & Hiking', 'Camp Kitchen', 'Stove Accessories', 'Fire Starters']]
 imUrl: http://ecx.images-amazon.com/images/I/41W6WE%2B4tdL._SX300_.jpg
-------- PREDICTION 0 --------
Title: Butler Creek LULA All-in-One Magazine Speed Loader and Unloader 223 Remington 5.56mm NATO
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Accessories', 'Magazine Loaders']]
 imUrl: http://ecx.images-amazon.com/images/I/419NdR8A-RL._SX300_.jpg
-------- PREDICTION 1 --------
Title: SwingTIP Golf Swing Analysis &amp; Coaching System
 Categories: [['Sports & Outdoors', 'Golf', 'Training Equipment', 'Swing Trainers']]
 imUrl: http://ecx.images-amazon.com/images/I/41AxwI4WjWL._SY300_.jpg
-------- PREDICTION 2 --------
Title: .30-30 Winchester 7.62x51mmR Caliber Cartridge Laser Bore Sighter Boresighter
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Boresighters']]
 imUrl: http://ecx.images-amazon.com/images/I/31U8hoaE8YL._SX300_.jpg
-------- GROUND-TRUTH --------
Title: AIM Cartridge Laser Rifle Bore Sighter For 7.62X39Mm
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Hunting Optics', 'Boresighters']]
 imUrl: http://ecx.images-amazon.com/images/I/31-FNk-IdPL._SY300_.jpg
-------- PREDICTION 0 --------
Title: Jandd Ankle Strap Black, Each
 Categories: [['Sports & Outdoors', 'Cycling']]
 imUrl: http://ecx.images-amazon.com/images/I/41-yDeSx1uL._SX300_.jpg
-------- PREDICTION 1 --------
Title: Magpul iPhone 4 Executive Field Case, Black
 Categories: [['Cell Phones & Accessories', 'Cases', 'Basic Cases'], ['Sports & Outdoors', 'Hunting & Fishing', 'Archery', 'Accessories', 'Bow Maintenance Accessories'], ['Sports & Outdoors', 'Hunting & Fishing', 'Archery', 'Accessories', 'Kisser Buttons']]
 imUrl: http://ecx.images-amazon.com/images/I/418cn7sV9kL._SY300_.jpg
-------- PREDICTION 2 --------
Title: Tipton Best Gun Vise
 Categories: [['Sports & Outdoors', 'Hunting & Fishing', 'Hunting', 'Gun Maintenance', 'Gunsmithing Tools']]
 imUrl: http://ecx.images-amazon.com/images/I/31qXlF7X1wL._SX300_.jpg